### PR TITLE
Social media links and icons updated in ReadMe file

### PR DESCRIPTION
**Pull request by sutirthverma**

### CODE REVIEW

**Comment by guyluz11** [comment]
Hi, can you please change pr to dev branch?
Thanks

**Comment by sutirthverma** [comment]
> Hi, can you please change pr to dev branch? Thanks

Done

**Comment by guyluz11** [comment]
Thanks for the pr @sutirthverma and a happy Hacktoberfest :D

**Comment by sutirthverma** [comment]
> Thanks for the pr @sutirthverma and a happy Hacktoberfest :D

Thank you so much 😄

**Pull request merged**
