### PR TITLE
Fix youtube link alignment

### LINKED ISSUE #73: YouTube logo in readme is not in the correct line
The YouTube logo in readme file (dev branch) suppose to be in a new line of its own

image

### PR DESCRIPTION
**Pull request by adripo**
Align youtube icon and text on new line.

fixes #73

### CODE REVIEW

**Comment by guyluz11** [comment]
> Does this looks good or do you like it better this way? https://github.com/adripo/security_bear/blob/patch-2/README.md

This one is good (the text to the right of the logo

Can you change the other icons to be in one line?
image

https://github.com/CyBear-Jinni/cbj_app/blob/master/README.md

**Comment by adripo** [comment]
@guyluz11 how about now?

**Comment by guyluz11** [comment]
@adripo that looks great :D

Thanks for the pr and a happy Hacktoberfest

**Comment by adripo** [comment]
Happy Hacktoberfest!

**Pull request merged**
