### PR TITLE
changed open source tag image

### PR DESCRIPTION
**Pull request by sakshi025**

### CODE REVIEW

**Comment by sakshi025** [comment]
see it now ...if it is clear or not ..

**Comment by guyluz11** [comment]
Looks good 😁

**Comment by guyluz11** [comment]
Thanks for the pr @sakshi025 
You can also change this image in the other repo's.

And a happy Hacktoberfest 🍻

**Comment by sakshi025** [comment]
you are welcomed @guyluz11 .
where to change the image ? in your repos or anyone else

**Comment by sakshi025** [comment]
and the image only changed in dev branch . Do u want it to be done in main branch also ?

**Comment by guyluz11** [comment]
Main branch has the same version as in the stores so it will take time for it to get pushed there.

> where to change the image ? in your repos or anyone else

The repos here
https://github.com/CyBear-Jinni

**Comment by sakshi025** [comment]
Are those repos also participating in hacktobefest 22?

**Comment by sakshi025** [comment]
@guyluz11 i had changed in your new repos.....please have a look

**Pull request merged**
